# Generated by Django 5.2.1 on 2025-05-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField()),
                ('p_color', models.CharField()),
                ('p_size', models.CharField()),
                ('p_qty', models.PositiveIntegerField()),
                ('p_photo', models.ImageField(upload_to='product')),
                ('p_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
