# Generated by Django 5.2.1 on 2025-05-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_prize',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
