# Generated by Django 5.2.1 on 2025-05-23 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_category',
        ),
    ]
